### PR TITLE
Remove recommendation for creation of labels

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR removes the recommendation to add labels to PRs and issues in CONTRIBUTING.md because community members do not have privileges to create labels in this repository (text adapted from [here](https://github.com/corona-warn-app/cwa-app-android/pull/2122))

This has been done 
- in the Android repository: https://github.com/corona-warn-app/cwa-app-android/pull/2122
- in the Website repository: https://github.com/corona-warn-app/cwa-website/pull/652

### CODE REVIEW

**Comment by dsarkar** [comment]
@Ein-Tim ok, I see. There are certain labels the community can use. Maybe it would be nice to include a sentence to use one of the available labels (bug, question, enhancement, ...) ?

Removed sencence:


 * Please apply one or more applicable [labels](https://github.com/corona-warn-app/cwa-documentation/labels) to your issue so that all community members are able to cluster the issues better.

**Comment by Ein-Tim** [comment]
@dsarkar 

Yes we could for sure go that way, I took the PR from @heinezen back in the website repo as basis, he removed the suggestion [completely](https://github.com/corona-warn-app/cwa-website/pull/652), so I also removed it. 

Just let me know what you want 👍

**Comment by MikeMcC399** [comment]
@dsarkar 
> There are certain labels the community can use. Maybe it would be nice to include a sentence to use one of the available labels (bug, question, enhancement, ...) ?

Community members do not have the privileges to add or remove labels. Labels like "Bug" are added through one of the files in [ISSUE_TEMPLATE](https://github.com/corona-warn-app/cwa-documentation/tree/master/.github/ISSUE_TEMPLATE). The label depends on which issue type the user chooses when they open a new issue and it can't be changed by the user subsequently. That is only something that somebody with more privileges can do. I can't see how that works exactly because I am only a Contributor so I don't have view access to the Settings of this repository!

@Ein-Tim's PR looks good; completely removing the sentence as was already done in the other repositories.

**Review by MikeMcC399 — APPROVED** [review]

**Comment by heinezen** [comment]
@MikeMcC399 @dsarkar @Ein-Tim 

Mike is correct in that non-members cannot assign or remove labels by themselves. The chosen template decides the initial labels of an issue.

**Review by heinezen — APPROVED** [review]
Makes sense. Let's do it.

**Pull request merged**
