### PR TITLE
Bump copyright year in README.md & README.de.md

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR bumps the copyright year in the README.md & README.de.md file.

Happy new year! 🎉

### Note

This PR should only be merged once a change to any content of this repository was done.

---
Internal Tracking ID: [EXPOSUREAPP-14521](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-14521)

### CODE REVIEW

**Review by brianebeling — APPROVED** [review]
Looks good, thanks!

**Comment by MikeMcC399** [comment]
Since there are no pending changes to this repository, I suggest to close this PR.

**Comment by Ein-Tim** [comment]
It's quite certain that there will be changes to this repository this year, so I would vote for just leaving the PR opened and merging it as soon as there were changes. This is also how it was done in most of the other repos.

**Comment by MikeMcC399** [comment]
I guess this PR could be merged since there have now been changes although it is stretching things to say that the removal of `alex` would be a copyrightable change!

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Thanks.

**Pull request merged**
