### PR TITLE
fix: Spellchecked and linted CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by dreh23**
Signed-off-by: Johannes Amorosa <johannes.amorosa@endocode.com>

### CODE REVIEW

**Comment by corneliusroemer** [comment]
Can you explain your suggestion a little? "Linting contributing according" ... to what?

**Comment by dreh23** [comment]
Sorry for the bad language. I corrected the headline.

**Comment by corneliusroemer** [comment]
Now it make sense, thanks!
So you added a few exceptions to spell checking and broke lines longer than 79 chars. Did I miss anything?

**Comment by dreh23** [comment]
Exactly. This file now conforms to the CI scripting.

**Comment by SebastianWolf-SAP** [comment]
Thanks for the pull request. Unfortunately, we decided against a line length limit - therefore, we can't merge this pull request. However, we enabled the markdown linter globally today and also integrated the spellcheck additions. See 7eca45d0b9783b262777a3d637256e5f316a755c, ec703906c109bd7c3cc84bc361b7e703b20650ea and 6ef01d9ee4951b4215b14b75fb2992b729ef5c5f.

Mit freundlichen Grüßen/Best regards, 
SW
Corona Warn-App Open Source Team

**Comment by corneliusroemer** [comment]
> Thanks for the pull request. Unfortunately, we decided against a line length limit - therefore, we can't merge this pull request. However, we enabled the markdown linter globally today and also integrated the spellcheck additions. See [7eca45d](https://github.com/corona-warn-app/cwa-documentation/commit/7eca45d0b9783b262777a3d637256e5f316a755c), [ec70390](https://github.com/corona-warn-app/cwa-documentation/commit/ec703906c109bd7c3cc84bc361b7e703b20650ea) and [6ef01d9](https://github.com/corona-warn-app/cwa-documentation/commit/6ef01d9ee4951b4215b14b75fb2992b729ef5c5f).
> 
> Mit freundlichen Grüßen/Best regards,
> SW
> Corona Warn-App Open Source Team

@SebastianWolf-SAP: Regarding your *unfortunately not being able to merge* line, I think unless @dreh23 explicitly disallowed maintainers from editing the PR you could have removed that part and still merged.

Out of courtesy, I think it would be nice if you mentioned @dreh23's PR/contribution in the commit message in the future, if you use the contribution in your own commit.

**Comment by SebastianWolf-SAP** [comment]
@corneliusroemer We really appreciate @dreh23's contributions. Without them, we wouldn't have the linter, spellchecker and related infrastructure. That was really a great addition and we actually wanted to honor that by using it to lint all the files in this repository. However, in this case it was simply easier to copy the three additional words to the .spelling file. As you can see in the commits, it was quite a lot of changes today...

**Pull request closed without merging**
