### PR TITLE
npm audit fix (fixes #497)

### LINKED ISSUE #497: Dependabot alerts
## Where to find the issue
npm configuration file
[package-lock.json](https://github.com/corona-warn-app/cwa-documentation/blob/master/package-lock.json)

## Describe the issue
GitHub Dependabot alerts on fork of https://github.com/corona-warn-app/cwa-documentation repository report vulnerable versions of npm packages defined in [package-lock.json](https://github.com/corona-warn-app/cwa-documentation/blob/master/package-lock.json):
1. ini, currently at version 1.3.5, should be upgraded to 1.3.6 or later
2. dot-prop, currently at version 4.2.0, should be upgraded to 4.2.1 or later

## Suggested change
run
`npm audit fix`

### PR DESCRIPTION
**Pull request by MikeMcC399**
This PR causes 
"ini" to be updated to 1.3.8 and
"dot-prop" to be updated to 4.2.1
in https://github.com/corona-warn-app/cwa-documentation/blob/master/package-lock.json which mitigates current Dependabot alerts for this repository.

It fixes Issue https://github.com/corona-warn-app/cwa-documentation/issues/497 and makes PR https://github.com/corona-warn-app/cwa-documentation/pull/480 obsolete.

`npm audit fix`
was run on a clone of the repository which generated an updated version of `package-lock.json`

`npm run test`
ran through after this update, producing the same (expected) error report about markdown formatting as previously.

### CODE REVIEW

**Comment by heinezen** [comment]
Hello @MikeMcC399 

This changes a lot of lines by adding a ``"packages"`` metadata field. How did you generate the package-lock file? Did you use `npm install --package-lock`?

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
> This changes a lot of lines by adding a "packages" metadata field. How did you generate the package-lock file? Did you use npm install --package-lock?

I did the minimum automated change which was 
`npm audit fix`
on a clone of the repository which generated an updated version of package-lock.json
See https://docs.npmjs.com/cli/v7/commands/npm-audit 

Running 
`npm install`
which I tried, makes even more changes. I discarded the change from `npm install` and committed only the change caused by running `npm audit fix`.

**Comment by heinezen** [comment]
`packages` is not specified in https://docs.npmjs.com/cli/v6/configuring-npm/package-lock-json#file-format so I don't know why it is included, but it being generated by `npm audit fix` could be the reason.

`npm install --package-lock` (note the flag) should only generate the package-lock.json file.

**Comment by heinezen** [comment]
Please rerun the chhanges from master with 

```
npm audit fix
npm install --package-lock
```

**Comment by MikeMcC399** [comment]
@heinezen 
Thanks for checking! I reverted my npm installation on Windows from 7.0.14 to the LTS version 6.14.10 which caused a much simpler change to package-lock.json after I ran
```
npm audit fix
npm install --package-lock
```
I don't believe the npm install instruction was necessary, but I ran it anyway.

After that, I tested on the master branch with:
```
npm run-script markdownlint
npm run-script checklinks
```
which both ran successfully.

I think package-lock.json should be OK for merging now.

**Comment by MikeMcC399** [comment]
Using npm 7.x introducing a different format for package-lock.json. I made a suggestion in https://github.com/corona-warn-app/cwa-documentation/issues/505 to document that npm 6.x from the LTS version of Node.js is needed / recommended instead of the current 7.x version of npm.

**Comment by heinezen** [comment]
@MikeMcC399 Can you squash you commits for merging? :)

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
> Can you squash you commits for merging? :)

I tried to do this with git, but I was unsuccessful. Could you just use "squash and merge" on this PR?

If you can tell me exactly what commands I need in git I could of course try again.
If everything else fails, I would close this PR and create another one which is clean.

**Comment by heinezen** [comment]
@MikeMcC399 You can usually do it in the CLI with 

```
git reset --soft HEAD~3
git commit -a
```

or in a git GUI (which is often nicer for getting an overview).

----
Corona-Warn-App Open Source Team

**Comment by MikeMcC399** [comment]
@heinezen 
Thanks for the tip. I will try that if necessary another time!

**Pull request merged**
