### PR TITLE
Include table with links to other repositories

### PR DESCRIPTION
**Pull request by Ein-Tim**
This PR adds a table with the links to other repos to the README.md file.
This is already done i.e. in the [iOS-Repo](https://github.com/corona-warn-app/cwa-app-ios/blob/release/1.11.x/README.md)

### CODE REVIEW

**Review by dsarkar — APPROVED** [review]

**Comment by Ein-Tim** [comment]
Please do not merge yet, there is one typo, I will correct it soon.

**Review by dsarkar — APPROVED** [review]

**Comment by MikeMcC399** [comment]
The commit [d677db7](https://github.com/corona-warn-app/cwa-documentation/commit/d677db79959cc172a2b2ffe5d9d682282d84ea77) associated with this merged PR (https://github.com/corona-warn-app/cwa-documentation/pull/493) failed the check
https://github.com/corona-warn-app/cwa-documentation/runs/1634788545

`README.md:103 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]`

referring to lines 102-103 in [README.md](https://github.com/corona-warn-app/cwa-documentation/blob/master/README.md).

**Comment by Ein-Tim** [comment]
@MikeMcC399 thanks for the hint...
There is one empty line to much (102,103). 
Maybe @mtb77 could simply push a commit to solve this. Of course I could also open a PR which fixes this.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Even if it is not a big point, it would be good to get the checks passing so that we notice any other errors which might be more serious. Let's wait to see what @mtb77 (or colleagues) think.

I made some suggestions in https://github.com/corona-warn-app/cwa-documentation/issues/495#issuecomment-753447986. Let me know if this is helpful and workable for you. Do you have a local clone of the repositories you are submitting changes to and if yes, what operating system is it running on? I have local clones of the forks running on Windows. (I also have an Ubuntu system running under VMware if I need it.)

**Comment by Ein-Tim** [comment]
@MikeMcC399 

I absolutely agree with you, the checks should be passing to note if anything more serious comes across... (Although it's a very bad situation at the moment, with the check running after merging the PR, but I see that you are on that). 

> Let me know if this is helpful and workable for you.

I can definitely activate the checks (=allow all actions) in my forked repos 👍

> Do you have a local clone of the repositories you are submitting changes to and if yes, what operating system is it running on?

Yes I have a local clone, but tbh I did not put this PR into it because node.js just returned weird errors (even without any changes from my side)...
I will investigate this, would it be ok if I come back to you via Slack DM if I need help with sth? 🙂

**Comment by MikeMcC399** [comment]
> @Ein-Tim 
> I can definitely activate the checks (=allow all actions) in my forked repos 👍

I think you only need to do this on the cwa-documentation repo at the moment, because it is the only one with a problem regarding actions / checks.

> I will investigate this, would it be ok if I come back to you via Slack DM if I need help with sth? 🙂

Sure. As you probably know, this is my first project using all these tools, so I am still heavily in the learning phase, but we can certainly exchange what we know via Slack DM.

**Comment by Ein-Tim** [comment]
Opened #500 @MikeMcC399

**Comment by mtb77** [comment]
@MikeMcC399  @Ein-Tim merged it - thanks!

**Pull request merged**
