### PR TITLE
docs(evreg): rephrase 3rd party information for integration

### PR DESCRIPTION
**Pull request by mlenkeit**

### CODE REVIEW

**Comment by Ein-Tim** [comment]
@mlenkeit 

Would you like to fix what has been mentioned in https://github.com/corona-warn-app/cwa-documentation/pull/592#issuecomment-826042199 by @MikeMcC399? 

I think this PR would be a good opportunity to do this.

**Comment by MikeMcC399** [comment]
@mlenkeit Thanks for picking up the comments from https://github.com/corona-warn-app/cwa-documentation/commit/d7525f18dd7bde76cce83fe8976d89d52ebfcd04!

1.  For third-party app providers it would be useful to describe the process for an app to become allowlisted.

2. Users would probably like to know which apps have already been accepted for integration, so a list of these apps would be helpful.

Let me know if it would be better to have separate issues opened for these two points.

**Comment by mlenkeit** [comment]
@MikeMcC399 valid points, but I think it makes sense to track both of these separately and independent of this PR. Feel free to create corresponding issues.

**Comment by MikeMcC399** [comment]
@mlenkeit 

> valid points, but I think it makes sense to track both of these separately and independent of this PR. Feel free to create corresponding issues.

Thanks for your feedback! I have created https://github.com/corona-warn-app/cwa-documentation/issues/602 and https://github.com/corona-warn-app/cwa-website/issues/1189 for further consideration.

**Pull request merged**
