### PR TITLE
feat: Override "alex" linting on CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by dreh23**
code of conduct file.

Signed-off-by: Johannes Amorosa <johannes.amorosa@endocode.com>

### CODE REVIEW

**Comment by corneliusroemer** [comment]
@dreh23 What exactly is the point of this PR? Would be good if you could explain a little more.

**Comment by dreh23** [comment]
Sure. #215 introduced a linter pipeline. One of the linter's utilizes https://github.com/get-alex/alex. Alex has an override [functionality](https://github.com/get-alex/alex#alexignore). I do not see the point to lint the Code of Conduct file, because of course here we define explicit wording - so linting would not make any sense.

**Comment by corneliusroemer** [comment]
@dreh23 Thanks now it makes sense!

**Comment by SebastianWolf-SAP** [comment]
Thanks!

**Pull request merged**
