### PR TITLE
Bump copyright year in README.md

### PR DESCRIPTION
**Pull request by Ein-Tim**
## Description

This PR bumps the copyright year in the README.md file.

Happy new year! 🎉

### Note

This PR should only be merged once a change to the content of this repository was done.

### CODE REVIEW

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Since the last commit in this repository (https://github.com/corona-warn-app/cwa-documentation/commit/9f51176f840df6ab840c43cc749900bd180f853e) was from Dec 2, 2021, there are no commits yet from 2022 and the commit frequency is quite low in this repository, it is too early to update the copyright year to include 2022.

It may become relevant again in the next weeks if there is a new commit to the repository.

**Comment by Ein-Tim** [comment]
I will leave this PR open, it can be merged when another change is done to the files in this repository.

**Comment by MikeMcC399** [comment]
@Ein-Tim 
Note that there is also a German version https://github.com/corona-warn-app/cwa-documentation/blob/master/translations/README.de.md which will soon need updating.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thanks, I updated the year in [`59a7d39`](https://github.com/corona-warn-app/cwa-documentation/pull/790/commits/59a7d39f75000f83dfbcc2b5c95e3f2db41b068c).

**Comment by dsarkar** [comment]
@Ein-Tim @MikeMcC399 Since I merged your PRs, we can merge this one as well. Thanks.

**Pull request merged**
